services:
  rss-bridge:
    image: lordarrin/rss-bridge:1.0.0
    container_name: rss-bridge2
    volumes:
      - /home/lordarrin/rssbridge2/config:/config
    ports:
      - "9999:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
