services:
  rss-bridge:
    image: lordarrin/rss-bridge:latest
    container_name: rss-bridge
    volumes:
      - /home/user/rssbridge/config:/config
    ports:
      - "3000:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
