name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  phpunit:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-versions: ['8.5']
    steps:
      - uses: actions/checkout@v5
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
        env:
          update: true
      - run: composer install --no-interaction
      - run: composer test